apiVersion: v1
kind: ConfigMap
metadata:
  name: l4d2-server-deployment-configmap
  namespace: l4d2-server-namespace
  labels:
    app: l4d2-server
data:
  USER_ID: "47120"
  PATH_SERVER: "/home/steam_user/files_server"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: l4d2-server-deployment
  namespace: l4d2-server-namespace
  labels:
    app: l4d2-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: l4d2-server
  template:
    metadata:
      labels:
        app: l4d2-server
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 8.8.8.8
      volumes:
        - name: l4d2-server-data
          persistentVolumeClaim:
            claimName: l4d2-server-pvc
      initContainers:
        - name: fix-ownership-vol
          image: busybox:latest
          env:
            - name: ownership_id
              valueFrom:
                configMapKeyRef:
                  name: l4d2-server-deployment-configmap
                  key: USER_ID
            - name: path_files_server
              valueFrom:
                configMapKeyRef:
                  name: l4d2-server-deployment-configmap
                  key: PATH_SERVER
          command: ["sh", "-c", 
                    "chown -R $(ownership_id):$(ownership_id) $(path_files_server);
                    chmod 750 $(path_files_server)"]
          volumeMounts:
            - name: l4d2-server-data
              mountPath: /home/steam_user/files_server
      containers:
      - name: l4d2-server
        image: serhiiartiukh5465/l4d2_dedicated_server
        ports:
          - containerPort: 27015
        volumeMounts:
          - name: l4d2-server-data
            mountPath: /home/steam_user/files_server
            
        
---
apiVersion: v1
kind: Service
metadata:
  name: l4d2-server-service
  namespace: l4d2-server-namespace
  labels:
    app: l4d2-server
spec:
  type: NodePort
  selector:
    app: l4d2-server
  ports:
    - name: server
      protocol: TCP
      port: 27015
      nodePort: 32451

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: l4d2-server-pv
  namespace: l4d2-server-namespace
  labels:
    app: l4d2-server
spec:
  capacity: 
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/media/k8s_pv/l4d2"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: l4d2-server-pvc
  namespace: l4d2-server-namespace
  labels:
    app: l4d2-server
spec:
  resources:
    requests:
      storage: 15Gi
  accessModes:
    - ReadWriteOnce