apiVersion: apps/v1
kind: Deployment
metadata:
  name: l4d2-server-deployment
  namespace: l4d2-server-namespace
  labels:
    app: l4d2-server
spec:
  selector:
    matchLabels:
      app: l4d2-server
  template:
    metadata:
      labels:
        app: l4d2-server
    spec:
      containers:
      - name: l4d2_server
        image: serhiiartiukh5465/l4d2_dedicated_server
        ports:
        - containerPort: 27015

---
apiVersion: v1
kind: Service
metadata:
  name: l4d2-server-deployment
spec:
  type: NodePort
  selector:
    app: l4d2-server
  ports:
  - port: 27015
    NodePort: 27015