services:
  l4d2_server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - USER_NAME=$USER_NAME
      - USER_ID=$USER_ID
      - PORT_SERVER=$PORT_SERVER
      - PATH_SERVER=$PATH_SERVER
    image: l4d2_dedicated_server
    container_name: l4d2_server
    ports:
      - $PORT_SERVER:$PORT_SERVER
      - $PORT_SERVER:$PORT_SERVER/udp
    volumes:
      - l4d2_server_data:${PATH_SERVER}
    tty: true

volumes:
  l4d2_server_data:
    external: true