services:
  l4d2_server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - USER_NAME=$USER_NAME
      - USER_ID=$USER_ID
      - PORT_SERVER=$PORT_SERVER
      - PATH_SERVER=$PATH_SERVER
    image: l4d2_dedicated_server
    container_name: l4d2_server
    ports:
      - $PORT_SERVER:$PORT_SERVER
      - $PORT_SERVER:$PORT_SERVER/udp
    volumes:
      - l4d2_server_data:${PATH_SERVER}
    tty: true
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '1G'
        reservations:
          cpus: '0.4'
          memory: '256M'

volumes:
  l4d2_server_data:
    external: true