apiVersion: v1
kind: ConfigMap
metadata:
  name: l4d2-server-deployment-configmap
  namespace: l4d2-server-namespace
  labels:
    app: l4d2-server
data:
  USER_ID: "47120"
  PATH_SERVER: "/home/steam_user/files_server"