apiVersion: v1
kind: PersistentVolume
metadata:
  name: l4d2-server-pv
  namespace: l4d2-server-namespace
  labels:
    app: l4d2-server
spec:
  capacity: 
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/media/k8s_pv/l4d2"