apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: l4d2-server-pvc
  namespace: l4d2-server-namespace
  labels:
    app: l4d2-server
spec:
  resources:
    requests:
      storage: 15Gi
  accessModes:
    - ReadWriteOnce