apiVersion: v1
kind: Service
metadata:
  name: l4d2-server-service
  namespace: l4d2-server-namespace
  labels:
    app: l4d2-server
spec:
  type: NodePort
  selector:
    app: l4d2-server
  ports:
    - name: server
      protocol: TCP
      port: 27015
      nodePort: 32451